create table books (
	id BIGSERIAL NOT NULL PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	genre VARCHAR(50) NOT NULL,
	author VARCHAR(50) NOT NULL,
	stock INT NOT NULL DEFAULT 1
);
insert into books (name, genre, author, stock) values ('Me and Morrison (Minä ja Morrison)', 'Romance', 'Laurena Pol', 26);
insert into books (name, genre, author, stock) values ('Ultramarines: A Warhammer 40,000 Movie', 'Animation|Sci-Fi', 'Raphael Piscot', 19);
insert into books (name, genre, author, stock) values ('From Here to Eternity', 'Drama|Romance|War', 'Butch Dadge', 6);
insert into books (name, genre, author, stock) values ('Other Dream Team, The', 'Documentary', 'Catrina Sizzey', 30);
insert into books (name, genre, author, stock) values ('Love Story', 'Drama|Romance', 'Vin Wontner', 20);
insert into books (name, genre, author, stock) values ('Coco Before Chanel (Coco avant Chanel)', 'Drama', 'Horace Brozek', 8);
insert into books (name, genre, author, stock) values ('Darwin Awards, The', 'Adventure|Comedy|Romance', 'Carson Ivanuschka', 27);
insert into books (name, genre, author, stock) values ('Jungle Fighters', 'Drama|War', 'Ferdinande Sherrett', 6);
insert into books (name, genre, author, stock) values ('Aileen Wuornos: The Selling of a Serial Killer', 'Documentary', 'Sonny Terran', 23);
insert into books (name, genre, author, stock) values ('Cactus Flower', 'Comedy', 'Jens Tucsell', 11);
insert into books (name, genre, author, stock) values ('Cook the Thief His Wife & Her Lover, The', 'Comedy|Drama', 'Rani De Minico', 15);
insert into books (name, genre, author, stock) values ('Silent Night, Deadly Night', 'Horror|Thriller', 'Kimberlee Brigman', 29);
insert into books (name, genre, author, stock) values ('Flicker (Flimmer)', 'Comedy|Drama', 'Kyla Crunden', 15);
insert into books (name, genre, author, stock) values ('Charlie Brown Christmas, A', 'Animation|Children|Comedy', 'Erin Christofle', 4);
insert into books (name, genre, author, stock) values ('Premonition', 'Drama|Fantasy|Mystery|Thriller', 'Bethina Probbing', 3);
insert into books (name, genre, author, stock) values ('Diary of Anne Frank, The', 'Drama|War', 'Cyndi Minchinden', 28);
insert into books (name, genre, author, stock) values ('Black Watch, The', 'Adventure|Drama', 'Philip Mazzey', 27);
insert into books (name, genre, author, stock) values ('Wild Thornberrys Movie, The', 'Animation|Children|Comedy', 'Ulrika Briat', 28);
insert into books (name, genre, author, stock) values ('Inferno', 'Horror', 'Serena Feria', 17);
insert into books (name, genre, author, stock) values ('Fear', 'Thriller', 'Leighton Bedells', 27);
insert into books (name, genre, author, stock) values ('White Man''s Burden', 'Drama', 'Patton Billows', 16);
insert into books (name, genre, author, stock) values ('Marie and Bruce', 'Comedy|Drama', 'Bowie Gussin', 14);
insert into books (name, genre, author, stock) values ('The Fearmakers', 'Thriller', 'Demetre Groome', 12);
insert into books (name, genre, author, stock) values ('Chimpanzee', 'Documentary', 'Micky Kirkebye', 28);
insert into books (name, genre, author, stock) values ('Elevator to the Gallows (a.k.a. Frantic) (Ascenseur pour l''échafaud)', 'Crime|Drama|Thriller', 'Stanleigh Ochiltree', 10);
insert into books (name, genre, author, stock) values ('Albert Nobbs', 'Drama', 'Axel Koomar', 24);
insert into books (name, genre, author, stock) values ('Have Dreams, Will Travel', 'Drama|Romance', 'Oswald Minchenton', 9);
insert into books (name, genre, author, stock) values ('Hitman, The', 'Action|Crime|Thriller', 'Jakob Nairn', 4);
insert into books (name, genre, author, stock) values ('I Am Michael', 'Drama', 'Natal Wardesworth', 11);
insert into books (name, genre, author, stock) values ('Pilgrim, The', 'Comedy', 'Way Oliff', 13);
insert into books (name, genre, author, stock) values ('13 Lakes', 'Documentary', 'Ludwig Ashtonhurst', 21);
insert into books (name, genre, author, stock) values ('Cremaster 5', 'Drama|Musical', 'Shanda Guillart', 16);
insert into books (name, genre, author, stock) values ('3 on a Couch (Three on a Couch)', 'Comedy|Romance', 'Babs Bentz', 15);
insert into books (name, genre, author, stock) values ('Diaries Notes and Sketches (Walden)', 'Documentary', 'Kassia Ambrozik', 9);
insert into books (name, genre, author, stock) values ('Romanzo Criminale', 'Crime|Drama', 'Georgeanne Manicom', 15);
insert into books (name, genre, author, stock) values ('Gen 13 (a.k.a. Gen13: The Animated Movie)', 'Action|Animation|Sci-Fi', 'Billy Deakes', 1);
insert into books (name, genre, author, stock) values ('Mating of Millie, The', 'Comedy|Romance', 'Tobiah Rignoldes', 19);
insert into books (name, genre, author, stock) values ('All the Pretty Horses', 'Drama|Romance|Western', 'Shelbi Willcocks', 19);
insert into books (name, genre, author, stock) values ('Double Confession', 'Crime|Drama', 'Mirilla Hardie', 21);
insert into books (name, genre, author, stock) values ('The Land Before Time VI: The Secret of Saurus Rock', 'Animation|Children', 'Reed Gall', 18);
insert into books (name, genre, author, stock) values ('Eclipse, The', 'Drama|Horror|Thriller', 'Major Burges', 28);
insert into books (name, genre, author, stock) values ('Wyrmwood', 'Action|Horror|Sci-Fi', 'Dulce Aguirrezabal', 22);
insert into books (name, genre, author, stock) values ('Angel-A', 'Comedy|Drama|Fantasy|Romance', 'Sancho Coils', 21);
insert into books (name, genre, author, stock) values ('Pusher II: With Blood on My Hands', 'Action|Crime|Drama|Thriller', 'Lemuel McArd', 19);
insert into books (name, genre, author, stock) values ('Lightning Jack', 'Comedy|Western', 'Haleigh Litster', 2);
insert into books (name, genre, author, stock) values ('Silent Partner, The', 'Crime|Drama|Thriller', 'Teddy Shubotham', 24);
insert into books (name, genre, author, stock) values ('You Were Never Lovelier', 'Comedy|Musical|Romance', 'Coraline Downs', 9);
insert into books (name, genre, author, stock) values ('Dylan Moran: Monster', 'Comedy|Documentary', 'Basia Curwen', 25);
insert into books (name, genre, author, stock) values ('Big Hangover, The', 'Comedy', 'Ches Streets', 24);
insert into books (name, genre, author, stock) values ('Landscape with a Woman (Zena s krajolikom)', 'Drama', 'Tyrone Vonasek', 21);
insert into books (name, genre, author, stock) values ('Boris and Natasha', 'Action|Comedy', 'Lita Raithbie', 25);
insert into books (name, genre, author, stock) values ('Snowblind', 'Western', 'Marianne Ruit', 9);
insert into books (name, genre, author, stock) values ('I''ll See You in My Dreams', 'Comedy|Drama', 'Evangelina Aldcorn', 15);
insert into books (name, genre, author, stock) values ('OH in Ohio, The', 'Comedy', 'Mandy Luciano', 27);
insert into books (name, genre, author, stock) values ('Demon Lover Diary', 'Documentary', 'Amara Sweeny', 11);
insert into books (name, genre, author, stock) values ('Sabotage', 'Action|Crime|Drama', 'Augustine Averies', 5);
insert into books (name, genre, author, stock) values ('After Hours', 'Comedy|Thriller', 'Nady Fairley', 2);
insert into books (name, genre, author, stock) values ('Vegas Vacation (National Lampoon''s Las Vegas Vacation)', 'Comedy', 'Jamaal Birrel', 17);
insert into books (name, genre, author, stock) values ('Gospel of John, The', 'Drama', 'Irita Marlen', 16);
insert into books (name, genre, author, stock) values ('Not Another Not Another Movie', 'Comedy', 'Lauritz Thackham', 24);
insert into books (name, genre, author, stock) values ('Lost in Yonkers', 'Comedy|Drama', 'Stephie MacCoughan', 21);
insert into books (name, genre, author, stock) values ('Socialism (Film socialisme)', 'Drama', 'Nobie Spurritt', 24);
insert into books (name, genre, author, stock) values ('Swordsman II (Legend of the Swordsman, The) (Xiao ao jiang hu zhi: Dong Fang Bu Bai)', 'Action|Fantasy', 'Gertrud Woofinden', 3);
insert into books (name, genre, author, stock) values ('Grocer''s Son, The (Fils de l''épicier, Le)', 'Drama|Romance', 'Noelle Dymoke', 28);
insert into books (name, genre, author, stock) values ('Monster', 'Crime|Drama', 'Farley Manntschke', 3);
insert into books (name, genre, author, stock) values ('Carny', 'Drama', 'Nonie Boner', 24);
insert into books (name, genre, author, stock) values ('Once Upon a Time in Mexico', 'Action|Adventure|Crime|Thriller', 'Grete Willars', 15);
insert into books (name, genre, author, stock) values ('The Russian Novel', 'Drama', 'Masha Nucator', 24);
insert into books (name, genre, author, stock) values ('Dead on Time', 'Comedy|Drama|Romance', 'Edyth Beedie', 12);
insert into books (name, genre, author, stock) values ('Mackintosh Man, The', 'Action|Drama|Thriller', 'Arlana Fairest', 26);
insert into books (name, genre, author, stock) values ('Your Highness', 'Action|Adventure|Comedy|Fantasy', 'Aylmer Fransson', 24);
insert into books (name, genre, author, stock) values ('Pepe', 'Comedy|Musical', 'Consalve Cockren', 30);
insert into books (name, genre, author, stock) values ('18 Years Old and Rising (J''aime regarder les filles)', 'Comedy', 'Millicent Darrigoe', 23);
insert into books (name, genre, author, stock) values ('North Star, The', 'Drama|Musical|Romance|War', 'Veronika Kolis', 4);
insert into books (name, genre, author, stock) values ('Escape from Suburbia: Beyond the American Dream', 'Documentary', 'Langston Radnage', 10);
insert into books (name, genre, author, stock) values ('Harmonists, The', 'Drama', 'Zita Cund', 30);
insert into books (name, genre, author, stock) values ('Cutter''s Way', 'Drama|Thriller', 'Trescha Byfield', 13);
insert into books (name, genre, author, stock) values ('The Lazarus Effect', 'Horror|Thriller', 'Matthew Granger', 19);
insert into books (name, genre, author, stock) values ('Million Dollar Mystery', 'Comedy', 'Poppy Skuce', 29);
insert into books (name, genre, author, stock) values ('Mobsters', 'Crime|Drama', 'Alie O''Bradden', 13);
insert into books (name, genre, author, stock) values ('My Name is Khan', 'Drama|Romance', 'Walliw Wickwarth', 13);
insert into books (name, genre, author, stock) values ('Substitute, The', 'Action|Crime|Drama', 'Tedra Laurenson', 24);
insert into books (name, genre, author, stock) values ('House on Haunted Hill', 'Drama|Horror|Thriller', 'Ermengarde De Vaan', 29);
insert into books (name, genre, author, stock) values ('Opfergang', 'Drama', 'Terrel Heavyside', 29);
insert into books (name, genre, author, stock) values ('Anna Karenina', 'Drama|Romance', 'Nicko Panther', 9);
insert into books (name, genre, author, stock) values ('Wedding Party, The (Die Bluthochzeit)', 'Action|Comedy|Drama', 'Bertie Hearne', 1);
insert into books (name, genre, author, stock) values ('Story of a Prostitute (Shunpu den)', 'Drama|War', 'Hurley Lambis', 27);
insert into books (name, genre, author, stock) values ('Marilyn Hotchkiss'' Ballroom Dancing & Charm School', 'Comedy|Drama|Romance', 'Lani Wallbridge', 20);
insert into books (name, genre, author, stock) values ('Dick Tracy', 'Action|Crime', 'Daffie Dowdall', 1);
insert into books (name, genre, author, stock) values ('Memento Mori (Yeogo goedam II)', 'Horror', 'Torrence Corn', 16);
insert into books (name, genre, author, stock) values ('Complete History of My Sexual Failures, A', 'Comedy|Documentary', 'Tyrone Jee', 5);
insert into books (name, genre, author, stock) values ('Behind the Sun (Abril Despedaçado)', 'Drama', 'Michel Bridgewater', 6);
insert into books (name, genre, author, stock) values ('World on a Wire (Welt am Draht)', 'Crime|Sci-Fi', 'Kerby Lemin', 21);
insert into books (name, genre, author, stock) values ('Diaries Notes and Sketches (Walden)', 'Documentary', 'Laura Oram', 15);
insert into books (name, genre, author, stock) values ('Wedding Bell Blues', 'Comedy', 'Patty Peaddie', 18);
insert into books (name, genre, author, stock) values ('Sound and Fury', 'Documentary', 'Mela Rooney', 3);
insert into books (name, genre, author, stock) values ('Wolverine, The', 'Action|Adventure|Fantasy|Sci-Fi', 'Nikolaus Child', 26);
insert into books (name, genre, author, stock) values ('Belarmino', 'Documentary|Drama', 'Claribel Bartolomeo', 4);
insert into books (name, genre, author, stock) values ('Ann Carver''s Profession', 'Drama', 'Adriena Fitzsymons', 18);
insert into books (name, genre, author, stock) values ('Adventures of Captain Marvel', 'Action|Adventure|Fantasy|Mystery|Sci-Fi', 'Dannie Tarbox', 3);
